[package]
name = "advent_of_code_2016"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
strum = "0.27.2"
strum_macros = "0.27.2"
